name = "cf-worker-777" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
UUID = "5A88C634-8BD0-4C27-BC5C-E1B0DC8D0FC5"
